version: "3.5"

services:
  web:
    image: ${docker_repo:-zokradonh}/kopano_web:${KWEB_VERSION:-latest}
    restart: always
    ports:
      - "2015:2015"
    environment:
      - DEFAULTREDIRECT=/grapi-explorer
      - EMAIL=off
      - FQDN=${FQDN}
      #- KONNECTPATH=meetid
    command: wrapper.sh
    volumes:
     - /etc/machine-id:/etc/machine-id
     - /etc/ssl/certs:/etc/ssl/certs:ro
     - /etc/machine-id:/var/lib/dbus/machine-id
    networks:
     - web-net

  kopano_ssl:
    image: ${docker_repo:-zokradonh}/kopano_ssl:${SSL_VERSION:-latest}
    environment:
      - FQDN=${FQDN}
      - PKI_COUNTRY=DE
    volumes:
      - kopanossl/:/kopano/ssl

  kopano_konnect:
    image: ${docker_repo:-zokradonh}/kopano_konnect:${KONNECT_VERSION:-latest}
    read_only: true
    restart: unless-stopped
    depends_on:
      - kopano_ssl
      - web
      # to be useful Konnect also needs a running kopano_server, but this dependency cannot be added here since this would be a circular dependency
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /etc/machine-id:/var/lib/dbus/machine-id
      - /run/kopano/:/run/kopano
      - kopanossl/:/kopano/ssl
      - /etc/ssl/certs:/etc/ssl/certs:ro
    environment:
      - allow_client_guests=yes
      - allow_dynamic_client_registration=yes
      - eckey=/kopano/ssl/meet-kwmserver.pem
      - ecparam=/kopano/ssl/ecparam.pem
      - encryption_secret_key=/kopano/ssl/konnectd-encryption.key
      - FQDN=${FQDN}
      - identifier_registration_conf=/kopano/ssl/konnectd-identifier-registration.yaml
      - identifier_scopes_conf=/etc/kopano/konnectd-identifier-scopes.yaml
      - signing_private_key=/kopano/ssl/konnectd-tokens-signing-key.pem
      - validation_keys_path=/kopano/ssl/konnectkeys
    networks:
      - kopano-net
      - web-net
    tmpfs:
      - /tmp

  kopano_grapi:
    image: ${docker_repo:-zokradonh}/kopano_core:${CORE_VERSION:-latest}
    read_only: true
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_grapi
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /etc/machine-id:/var/lib/dbus/machine-id
      - kopanograpi/:/var/lib/kopano-grapi
      - /run/kopano/:/run/kopano
    environment:
      - KCCONF_GRAPI_ENABLE_EXPERIMENTAL_ENDPOINTS=yes # needs to be set to yes for grapi versions prior to 10.3 to use calendar
      - KCCONF_GRAPI_INSECURE=${INSECURE}
      - KCCONF_GRAPI_PERSISTENCY_PATH=/var/lib/kopano-grapi
      - SERVICE_TO_START=grapi
      - TZ=${TZ}
    networks:
      - kopano-net
      - web-net
    tmpfs:
      - /tmp/

  kopano_kapi:
    image: ${docker_repo:-zokradonh}/kopano_core:${CORE_VERSION:-latest}
    read_only: true
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_kapi
    depends_on:
      - kopano_grapi
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /etc/machine-id:/var/lib/dbus/machine-id
      - kopanodata/:/kopano/data
      - /run/kopano/:/run/kopano
      - kopanossl/:/kopano/ssl
      - /etc/ssl/certs:/etc/ssl/certs:ro
    environment:
      - DEFAULT_PLUGIN_PUBS_SECRET_KEY_FILE=/kopano/ssl/kapid-pubs-secret.key
      - KCCONF_KAPID_INSECURE=${INSECURE}
      - KCCONF_KAPID_LISTEN=0.0.0.0:8039
      - KCCONF_KAPID_LOG_LEVEL=DEBUG
      - KCCONF_KAPID_LOG_LEVEL=info
      - KCCONF_KAPID_OIDC_ISSUER_IDENTIFIER=https://${FQDN}
      - KCCONF_KAPID_PLUGIN_GRAPI_SOCKET_PATH=/var/run/kopano/grapi
      - KCCONF_KAPID_PLUGIN_KVS_DB_DATASOURCE=/kopano/data/kapi-kvs/kvs.db
      - SERVICE_TO_START=kapi
      - TZ=${TZ}
    networks:
      - kopano-net
      - web-net
    tmpfs:
      - /tmp

  kopano_grapi-explorer:
    image: kopano/grapi-explorer
    restart: unless-stopped
    depends_on:
      - kopano_kapi
      - kopano_konnect
    environment:
      - GRAPI_EXPLORER_ISS=https://${FQDN}
      - GRAPI_EXPLORER_GRAPH_URL=https://${FQDN}/api/gc
    networks:
      - kopano-net
      - web-net

volumes:
    kopanossl:
    kopanodata:
    kopanograpi:

networks:
  kopano-net:
    driver: bridge
  web-net: